import requests
import waveassist
from datetime import datetime, timezone

# Initialize WaveAssist
waveassist.init(check_credits=True)

# Constants - identifiers for GitZoid comments
INTRO_COMMENT = "_Here's an automated AI-generated review to support your development workflow._\n\n"
FOOTER_COMMENT = "---\n\n _This review was generated by [Gitzoid](https://waveassist.io/assistants/gitzoid), an AI-powered code review assistant._"

# Incremental review header
INCREMENTAL_INTRO = "🔄 _New commits detected! Here's an updated review based on the latest changes._\n\n"


def format_array_to_markdown(items: list) -> str:
    """Convert a Python list to markdown bullet points."""
    if not items:
        return ""
    return "\n".join([f"- {item}" for item in items])


def generate_full_comment(review_dict: dict) -> str:
    """Generate comment for full (first-time) PR review."""
    summary = review_dict.get("summary", [])
    potential_issues = review_dict.get("potential_issues", [])
    potential_optimizations = review_dict.get("potential_optimizations", [])
    suggestions = review_dict.get("suggestions", [])
    
    output_comment = INTRO_COMMENT
    
    if summary:
        formatted_summary = format_array_to_markdown(summary)
        output_comment += f"## 📝 Summary\n\n{formatted_summary}\n\n"
    if potential_issues:
        formatted_issues = format_array_to_markdown(potential_issues)
        output_comment += f"## ⚠️ Potential Issues\n\n{formatted_issues}\n\n"
    if potential_optimizations:
        formatted_optimizations = format_array_to_markdown(potential_optimizations)
        output_comment += f"## 🚀 Potential Optimizations\n\n{formatted_optimizations}\n\n"
    if suggestions:
        formatted_suggestions = format_array_to_markdown(suggestions)
        output_comment += f"## 💡 Suggestions\n\n{formatted_suggestions}\n\n"
    
    output_comment += FOOTER_COMMENT
    return output_comment


def generate_incremental_comment(review_dict: dict, previous_sha: str = "", current_sha: str = "") -> str:
    """Generate comment for incremental PR review after new commits."""
    # Ensure all expected keys exist (defensive programming for IncrementalReviewResult)
    if not isinstance(review_dict, dict):
        review_dict = {}
    changes_summary = review_dict.get("changes_summary", [])
    addressed_issues = review_dict.get("addressed_issues", [])
    new_observations = review_dict.get("new_observations", [])
    
    sha_info = ""
    if previous_sha and current_sha:
        sha_info = f"_Reviewing changes from `{previous_sha[:7]}` → `{current_sha[:7]}`_\n\n"
    
    output_comment = INCREMENTAL_INTRO + sha_info
    
    if changes_summary:
        formatted_changes = format_array_to_markdown(changes_summary)
        output_comment += f"## 📋 Changes Summary\n\n{formatted_changes}\n\n"
    
    if addressed_issues:
        formatted_addressed = format_array_to_markdown(addressed_issues)
        output_comment += f"## ✅ Addressed Issues\n\n{formatted_addressed}\n\n"
    
    if new_observations:
        formatted_new = format_array_to_markdown(new_observations)
        output_comment += f"## 🔍 New Observations\n\n{formatted_new}\n\n"
    
    output_comment += FOOTER_COMMENT
    return output_comment


def post_pr_comment(repo_path: str, pr_number: int, body: str, token: str):
    """
    Post a comment to a GitHub PR via the Issues API.
    Returns the JSON response on success, or None on failure.
    """
    url = f"https://api.github.com/repos/{repo_path}/issues/{pr_number}/comments"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
    }
    resp = requests.post(url, headers=headers, json={"body": body})
    if resp.status_code == 201:
        print(f"✅ Comment posted to {repo_path} PR #{pr_number}")
        return resp.json()
    print(f"❌ Failed to post comment (HTTP {resp.status_code}): {resp.json()}")
    return None


def update_reviewed_prs(reviewed_prs: dict, repo_path: str, pr_number: int, current_sha: str, review_text: str = None):
    """
    Update the reviewed_prs tracker with the latest reviewed SHA, timestamp, and review text.
    Key format: "{repo_path}#{pr_number}"
    """
    pr_key = f"{repo_path}#{pr_number}"
    reviewed_prs[pr_key] = {
        "status": "reviewed",
        "last_reviewed_sha": current_sha,
        "reviewed_at": datetime.now(timezone.utc).isoformat(),
    }
    if review_text:
        reviewed_prs[pr_key]["last_review_text"] = review_text


# Fetch inputs
prs_to_review = waveassist.fetch_data("pull_requests") or []
should_process = False

for pr in prs_to_review:
    if pr.get("comment_generated") and not pr.get("comment_posted"):
        should_process = True
        break

if should_process:
    github_token = waveassist.fetch_data("github_access_token")
    reviewed_prs = waveassist.fetch_data("reviewed_prs") or {}
    
    display_output_content = "<div style=\"font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 16px; line-height: 1.5;\">"
    
    if not github_token:
        raise RuntimeError("❌ Missing `github_access_token`; cannot post PR comments.")

    reviewed_prs_changed = False

    # Process each PR
    for pr in prs_to_review:
        if not pr.get("comment_generated") or pr.get("comment_posted"):
            continue
        
        review_dict = pr.get("review_dict", {})
        if not review_dict:
            continue

        repo_path = pr["id"]
        pr_number = pr["pr_number"]
        review_type = pr.get("review_type", "full")
        current_sha = pr.get("current_sha", "")
        
        # Generate comment based on review type
        if review_type == "incremental":
            # Generate incremental comment
            full_body = generate_incremental_comment(
                review_dict,
                previous_sha=pr.get("previous_sha", ""),
                current_sha=current_sha
            )
            review_label = "incremental"
        else:
            # Generate full comment for new PRs
            full_body = generate_full_comment(review_dict)
            review_label = "full"
        
        result = post_pr_comment(
            repo_path,
            pr_number,
            full_body,
            github_token,
        )
        
        if result:
            pr["comment_posted"] = True
            pr["files"] = []  # clear diffs for privacy
            
            # Update reviewed_prs tracker with current SHA and review text
            if current_sha:
                update_reviewed_prs(reviewed_prs, repo_path, pr_number, current_sha, full_body)
                reviewed_prs_changed = True
            
            display_output_content += f'<div style="margin-bottom: 8px; color: #28a745;">✅ {review_label.title()} review posted to <strong>{repo_path}</strong> PR #{pr_number}</div>'

    # Persist updates
    display_output_content += '<div style="margin-top: 12px; color: #28a745;">✅ Repositories and PRs updated successfully.</div></div>'
    
    # Only store reviewed_prs if changed
    if reviewed_prs_changed:
        waveassist.store_data("reviewed_prs", reviewed_prs)
    
    waveassist.store_data("pull_requests", [])
    waveassist.store_data(
        "display_output", {"html_content": display_output_content}, run_based=True
    )
    print("✅ Repositories and PRs updated successfully.")
